import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import localFont from "next/font/local";
import { authOptions } from "./api/auth /[...nextauth]/route";
import "./globals.css";
import NextAuthProvider from "./provider/NextAuthProvider";
import { ThemeProvider } from "./ThemeProvider";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <NextAuthProvider session={session}>
            <ThemeProvider>{children}</ThemeProvider>
          </NextAuthProvider>
      </body>
    </html>
  );
}
